### ISSUE TITLE
Allow to override the docstrings for fields

### ISSUE THREAD

**Issue by rixx** [edoburu/sphinxcontrib-django#14]
If I have a simple model, and the verbose_name or help_text is public-facing and not what I'd like to see in my developer docs, I want to override the `sphinxcontrib-django` doc string by providing my own – but instead of overriding, I now have the same field documented twice.

(Bonus bug: the `(SomeField)` annotation provided by this package is found with the added to my additional documentation, not to the one generated by this package.)

**Comment by vdboor** [comment]
Merged, and fixed! Thanks!
