### ISSUE TITLE
Error in "inheritance-diagram" directive: 1 argument(s) required, 0 supplied.

### ISSUE THREAD

**Issue by dtomas** [edoburu/sphinxcontrib-django#45]
When using `sphinxcontrib-django` together with `sphinx.ext.inheritance_diagram` in Sphinx 4.4.0, the following error occurs for each model class docstring:
```
ERROR: Error in "inheritance-diagram" directive:
1 argument(s) required, 0 supplied.

.. inheritance-diagram::
```

**Comment by timobrembeck** [comment]
@dtomas Thanks a lot for the report, I hope I resolved the issue, could you install the newest version and check again?
